/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  socialImage?: EditorialImage;
};

export type Divider = {
  _type: "divider";
  style: string;
};

export type ArticleNote = {
  _type: "articleNote";
  label?: string;
  text: string;
};

export type PullQuote = {
  _type: "pullQuote";
  text: string;
  attribution?: string;
};

export type ArticleFigure = {
  _type: "articleFigure";
  image: EditorialImage;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type EditorialImage = {
  _type: "editorialImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  caption?: string;
  credit: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  section: "FIELD" | "CINEMA" | "ESSAYS";
  category:
    | "Attention"
    | "Culture"
    | "Design"
    | "Editing"
    | "Essay"
    | "History"
    | "Ideas"
    | "Image"
    | "Internet"
    | "Life"
    | "Match"
    | "Memory"
    | "Moviegoing"
    | "Notebook"
    | "Objects"
    | "Performance"
    | "Places"
    | "Players"
    | "Relationships"
    | "Screenwriting"
    | "Sound"
    | "Tactics"
    | "Technology"
    | "Work";
  mode: "FEATURE" | "STANDARD" | "ESSAY";
  kicker?: string;
  dek: string;
  opening?: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3";
        listItem?: "bullet" | "number";
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & PullQuote)
    | ({
        _key: string;
      } & ArticleFigure)
    | ({
        _key: string;
      } & Divider)
    | ({
        _key: string;
      } & ArticleNote)
  >;
  author: AuthorReference;
  publishedAt: string;
  readingTimeOverride?: number;
  leadImage?: EditorialImage;
  relatedArticles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  bio: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Seo
  | Divider
  | ArticleNote
  | PullQuote
  | ArticleFigure
  | SanityImageAssetReference
  | EditorialImage
  | AuthorReference
  | ArticleReference
  | Article
  | Author
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: ARTICLE_QUERY
// Query: *[    _type == "article" &&    section == $section &&    slug.current == $slug &&    defined(publishedAt)  ][0]{    _id,    title,    "slug": slug.current,    section,    category,    mode,    dek,    kicker,    opening,    publishedAt,    readingTimeOverride,    leadImage{      asset->{_id, _type, url, metadata{dimensions{width, height, aspectRatio}}},      crop,      hotspot,      alt,      caption,      credit    },    body[]{      ...,      _type == "articleFigure" => {        _type,        image{          asset->{_id, _type, url, metadata{dimensions{width, height, aspectRatio}}},          crop,          hotspot,          alt,          caption,          credit        }      }    },    author->{_id, name, "slug": slug.current, bio},    relatedArticles[]->{      _id,      title,      "slug": slug.current,      section,      category,      dek,      publishedAt,      "author": author->name,      leadImage{        asset->{_id, _type, url, metadata{dimensions{width, height, aspectRatio}}},        crop,        hotspot,        alt,        caption,        credit      }    },    seo{      title,      description,      socialImage{        asset->{_id, _type, url, metadata{dimensions{width, height, aspectRatio}}},        crop,        hotspot,        alt,        caption,        credit      }    }  }
export type ARTICLE_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  section: "CINEMA" | "ESSAYS" | "FIELD";
  category:
    | "Attention"
    | "Culture"
    | "Design"
    | "Editing"
    | "Essay"
    | "History"
    | "Ideas"
    | "Image"
    | "Internet"
    | "Life"
    | "Match"
    | "Memory"
    | "Moviegoing"
    | "Notebook"
    | "Objects"
    | "Performance"
    | "Places"
    | "Players"
    | "Relationships"
    | "Screenwriting"
    | "Sound"
    | "Tactics"
    | "Technology"
    | "Work";
  mode: "ESSAY" | "FEATURE" | "STANDARD";
  dek: string;
  kicker: string | null;
  opening: string | null;
  publishedAt: string;
  readingTimeOverride: number | null;
  leadImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      url: string;
      metadata: {
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string;
    caption: string | null;
    credit: string;
  } | null;
  body: Array<
    | {
        _key: string;
        _type: "articleFigure";
        image: {
          asset: {
            _id: string;
            _type: "sanity.imageAsset";
            url: string;
            metadata: {
              dimensions: {
                width: number;
                height: number;
                aspectRatio: number;
              } | null;
            } | null;
          } | null;
          crop: SanityImageCrop | null;
          hotspot: SanityImageHotspot | null;
          alt: string;
          caption: string | null;
          credit: string;
        };
      }
    | {
        _key: string;
        _type: "articleNote";
        label?: string;
        text: string;
      }
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "divider";
        style: string;
      }
    | {
        _key: string;
        _type: "pullQuote";
        text: string;
        attribution?: string;
      }
  >;
  author: {
    _id: string;
    name: string;
    slug: string;
    bio: string;
  };
  relatedArticles: Array<{
    _id: string;
    title: string;
    slug: string;
    section: "CINEMA" | "ESSAYS" | "FIELD";
    category:
      | "Attention"
      | "Culture"
      | "Design"
      | "Editing"
      | "Essay"
      | "History"
      | "Ideas"
      | "Image"
      | "Internet"
      | "Life"
      | "Match"
      | "Memory"
      | "Moviegoing"
      | "Notebook"
      | "Objects"
      | "Performance"
      | "Places"
      | "Players"
      | "Relationships"
      | "Screenwriting"
      | "Sound"
      | "Tactics"
      | "Technology"
      | "Work";
    dek: string;
    publishedAt: string;
    author: string;
    leadImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
      caption: string | null;
      credit: string;
    } | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    socialImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        url: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
            aspectRatio: number;
          } | null;
        } | null;
      } | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
      alt: string;
      caption: string | null;
      credit: string;
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: ARTICLE_SLUGS_QUERY
// Query: *[    _type == "article" &&    section == $section &&    defined(slug.current) &&    defined(publishedAt) &&    defined(title) &&    defined(dek) &&    defined(category) &&    defined(mode) &&    defined(body[0]) &&    defined(author->._id)  ] | order(slug.current asc) {    "slug": slug.current  }
export type ARTICLE_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: ARTICLE_SUMMARIES_QUERY
// Query: *[    _type == "article" &&    section == $section &&    defined(slug.current) &&    defined(publishedAt)  ] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    section,    category,    dek,    publishedAt,    "author": author->name,    leadImage{      asset->{_id, _type, url, metadata{dimensions{width, height, aspectRatio}}},      crop,      hotspot,      alt,      caption,      credit    }  }
export type ARTICLE_SUMMARIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  section: "CINEMA" | "ESSAYS" | "FIELD";
  category:
    | "Attention"
    | "Culture"
    | "Design"
    | "Editing"
    | "Essay"
    | "History"
    | "Ideas"
    | "Image"
    | "Internet"
    | "Life"
    | "Match"
    | "Memory"
    | "Moviegoing"
    | "Notebook"
    | "Objects"
    | "Performance"
    | "Places"
    | "Players"
    | "Relationships"
    | "Screenwriting"
    | "Sound"
    | "Tactics"
    | "Technology"
    | "Work";
  dek: string;
  publishedAt: string;
  author: string;
  leadImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      url: string;
      metadata: {
        dimensions: {
          width: number;
          height: number;
          aspectRatio: number;
        } | null;
      } | null;
    } | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    alt: string;
    caption: string | null;
    credit: string;
  } | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[\n    _type == "article" &&\n    section == $section &&\n    slug.current == $slug &&\n    defined(publishedAt)\n  ][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    section,\n    category,\n    mode,\n    dek,\n    kicker,\n    opening,\n    publishedAt,\n    readingTimeOverride,\n    leadImage{\n      asset->{_id, _type, url, metadata{dimensions{width, height, aspectRatio}}},\n      crop,\n      hotspot,\n      alt,\n      caption,\n      credit\n    },\n    body[]{\n      ...,\n      _type == "articleFigure" => {\n        _type,\n        image{\n          asset->{_id, _type, url, metadata{dimensions{width, height, aspectRatio}}},\n          crop,\n          hotspot,\n          alt,\n          caption,\n          credit\n        }\n      }\n    },\n    author->{_id, name, "slug": slug.current, bio},\n    relatedArticles[]->{\n      _id,\n      title,\n      "slug": slug.current,\n      section,\n      category,\n      dek,\n      publishedAt,\n      "author": author->name,\n      leadImage{\n        asset->{_id, _type, url, metadata{dimensions{width, height, aspectRatio}}},\n        crop,\n        hotspot,\n        alt,\n        caption,\n        credit\n      }\n    },\n    seo{\n      title,\n      description,\n      socialImage{\n        asset->{_id, _type, url, metadata{dimensions{width, height, aspectRatio}}},\n        crop,\n        hotspot,\n        alt,\n        caption,\n        credit\n      }\n    }\n  }\n': ARTICLE_QUERY_RESULT;
    '\n  *[\n    _type == "article" &&\n    section == $section &&\n    defined(slug.current) &&\n    defined(publishedAt) &&\n    defined(title) &&\n    defined(dek) &&\n    defined(category) &&\n    defined(mode) &&\n    defined(body[0]) &&\n    defined(author->._id)\n  ] | order(slug.current asc) {\n    "slug": slug.current\n  }\n': ARTICLE_SLUGS_QUERY_RESULT;
    '\n  *[\n    _type == "article" &&\n    section == $section &&\n    defined(slug.current) &&\n    defined(publishedAt)\n  ] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    section,\n    category,\n    dek,\n    publishedAt,\n    "author": author->name,\n    leadImage{\n      asset->{_id, _type, url, metadata{dimensions{width, height, aspectRatio}}},\n      crop,\n      hotspot,\n      alt,\n      caption,\n      credit\n    }\n  }\n': ARTICLE_SUMMARIES_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
